version: "3.8"

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      target: production
    ports:
      - 4000:4000
    environment:
      - REDIS_HOST=redis
