version: "3.8"

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      target: development
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
      - 4000:4000
    environment:
      - REDIS_HOST=redis
    command: npm run dev
